name: Use GitHub Secret in Python

on: [push]  # Runs this workflow when you push code

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python Script
        env:
          shift: ${{ secrets.CSHIFT }}
          vign: ${{ secrets.VIGNKEY }}
          subs: ${{ secrets.SUBS_KEY }}
        run: python script.py
